name: thin_logger
description: A minimal logger class, suitable mostly for console utilities rather than enterprise-grade applications.
version: 0.1.2
homepage: https://aiurovet.blogspot.com/

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
