name: thin_logger
description: A minimal logger class, suitable mostly for console utilities rather than enterprise-grade applications.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
