name: thin_logger
description: A minimal logger class, suitable mostly for console utilities rather than enterprise-grade applications.
version: 0.1.3
homepage: https://aiurovet.blogspot.com/
repository: https://github.com/aiurovet/thin_logger/

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
